// location: components/gallery/gallery.data.js
export const GALLERY = {
  collections: [
    {
      id: "commercial",
      title: "Commercial",
      subtitle: "Site planning, entries, and amenity spaces for commercial developments.",
      coverImage: "/images/gallery/covers/commercial.jpg",
      tags: ["design", "commercial"],
      items: [
        {
          id: "commercial-001",
          type: "image",
          src: "/images/gallery/items/commercial-001.jpg",
          alt: "Woodhaven Village — Entry drive and landscape",
          caption: "Entry sequence with native plantings and stone features.",
          featured: true,
        },
        {
          id: "commercial-002",
          type: "image",
          src: "/images/gallery/items/commercial-002.jpg",
          alt: "Vargos on the Lake — Commercial landscape",
          caption: "Lakefront commercial development with natural stone.",
          featured: false,
        },
        {
          id: "commercial-003",
          type: "image",
          src: "/images/gallery/items/commercial-003.jpg",
          alt: "Office entry — Landscape architecture",
          caption: "Refined entry plaza with integrated lighting.",
          featured: true,
        },
      ],
    },
    {
      id: "residential",
      title: "Residential",
      subtitle: "Custom estate landscapes and outdoor living environments.",
      coverImage: "/images/gallery/covers/residential.jpg",
      tags: ["design", "residential"],
      items: [
        {
          id: "residential-001",
          type: "image",
          src: "/images/gallery/items/residential-001.jpg",
          alt: "Carlton Woods Estate — Pool and outdoor living",
          caption: "Resort-style outdoor living with custom pool and kitchen.",
          featured: true,
        },
        {
          id: "residential-002",
          type: "image",
          src: "/images/gallery/items/residential-002.jpg",
          alt: "Southfork Estates — Garden landscape",
          caption: "Multi-acre estate with formal and naturalized gardens.",
          featured: true,
        },
        {
          id: "residential-003",
          type: "image",
          src: "/images/gallery/items/residential-003.jpg",
          alt: "The Reserve — Private garden",
          caption: "Elegant residential landscape with focus on entertaining.",
          featured: false,
        },
      ],
    },
    {
      id: "construction",
      title: "Construction",
      subtitle: "Precision execution from grading to final planting.",
      coverImage: "/images/gallery/covers/construction.jpg",
      tags: ["build", "construction"],
      items: [
        {
          id: "construction-001",
          type: "image",
          src: "/images/gallery/items/construction-001.jpg",
          alt: "Hardscape construction — Stone patio",
          caption: "Custom stone patio with integrated fire feature.",
          featured: true,
        },
        {
          id: "construction-002",
          type: "image",
          src: "/images/gallery/items/construction-002.jpg",
          alt: "Landscape installation — Planting phase",
          caption: "Expert plant installation with attention to mature form.",
          featured: false,
        },
      ],
    },
  ],
};